from docx import Document
doc = Document()
doc.add_heading('MEMORANDUM OF UNDERSTANDING', 0)
doc.add_paragraph('This MOU is entered into as of 1 June 2025 between TechCorp Pte Ltd, a company incorporated in Singapore (UEN: 202512345A) ("Party A"); and Malaysia Manufacturing Sdn Bhd, a company incorporated in Malaysia ("Party B").')
doc.add_heading('1. PURPOSE', 1)
doc.add_paragraph('The Parties intend to explore a potential business collaboration for the distribution of software products in Southeast Asia.')
doc.add_heading('2. GOVERNING LAW', 1)
doc.add_paragraph('This MOU shall be governed by and construed in accordance with the laws of Singapore.')
doc.add_heading('3. CONFIDENTIALITY', 1)
doc.add_paragraph('Each Party agrees to keep confidential all information disclosed by the other Party in connection with this MOU.')
doc.add_heading('4. NON-COMPETE', 1)
doc.add_paragraph('During the term of this MOU and for 24 months thereafter, neither Party shall engage in any business that directly competes with the other Party in Singapore or the region.')
doc.add_heading('5. DISPUTE RESOLUTION', 1)
doc.add_paragraph('Any dispute arising out of this MOU shall be resolved by arbitration under the SIAC Rules in Singapore.')
doc.add_heading('6. DATA PROTECTION', 1)
doc.add_paragraph('Each Party shall comply with the Personal Data Protection Act 2012 (Singapore) in respect of any personal data processed under this MOU.')
doc.add_heading('7. TERM', 1)
doc.add_paragraph('This MOU shall be valid for 12 months from the date of signing unless terminated earlier by either Party on 30 days written notice.')
doc.add_heading('8. NON-BINDING', 1)
doc.add_paragraph('This MOU is not legally binding and does not create any legal obligations between the Parties, except for Clauses 3 and 4 which shall be binding.')
doc.save('test_sg_my_mou.docx')
print('Created: test_sg_my_mou.docx')
